name: Metrics
on:
  # Se ejecuta autom치ticamente cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pesta침a Actions
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu usuario
          user: Abrahamx9-R
          token: ${{ secrets.GITHUB_TOKEN }}

          # Configuraci칩n Visual
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Mexico_City
          
          # 1. Plugin de Lenguajes (Reemplaza a top-langs)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage

          # 2. Plugin de Logros/Trofeos (Reemplaza a trophies)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C # Muestra logros desde nivel C
          
          # 3. Plugin de H치bitos (Extra para rellenar)
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
